title: Home
email: tzu-yuan.huang@tum.de
keywords: tzu-yuan huang, tzuyuan huang, tyhuang, ian
description: >- # this means to ignore newlines until "baseurl:"
  Tzu-Yuan Huang (Ian) is a PhD student in information oriented control (ITR) chair, tecnical university in Munich (TUM), and supervised by Prof. Sandra Hirche. 
  His research interests include machine learning, safe control, generative model, and robotics. 
baseurl: "" # the subpath of your site, e.g. /blog
domain: ianhuangyh.github.io
url: "https://ianhuangyh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

teaser: /assets/images/passport_img.jpeg
# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: air
plugins:
  - jekyll-include-cache

author:
  name: "Tzu-Yuan Huang"
  avatar: "/assets/images/passport_img.jpeg"
  bio: "Ph.D. student in Tum" # Note: Markdown is allowed
  location: "Munich, Germany"
  links:
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/ian-huang-a06084148/"
    - label: "CV"
      icon: "far fa-fw fa-file-pdf"
      url: "/assets/files/cv.pdf"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=4K6xdGUAAAAJ"
    - label: "Lab"
      icon: "fas fa-school"
      url: "https://www.ce.cit.tum.de/en/itr/team/huang/"
    
atom_feed:
  hide: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/